import { Router } from 'express';
import { AuthRoutes } from '../modules/Auth/auth.routes';
import { UserRoutes } from '../modules/User/user.routes';
import aboutRouter from '../modules/about/about.route';
import privacyPolicyRouter from '../modules/PrivacyPolicy/privacyPolicy.routes';
import termsRouter from '../modules/Terms/terms.route';
import { FaqRoutes } from '../modules/FAQ/faq.routes';
import { ContactRoutes } from '../modules/ContactUs/contact.route';
import { NotificationRoutes } from '../modules/Notification/notification.routes';
import { ReviewRoutes } from '../modules/Review/review.routes';
import { AdminRoutes } from '../modules/Admin/admin.routes';
import { CategoryRoutes } from '../modules/ServiceCategory/category.routes';
import { SubcategoryRoutes } from '../modules/ServiceSubcategory/subcategory.routes';
import { AmenityRoutes } from '../modules/Amenity/amenity.routes';
import { ServiceAreaRoutes } from '../modules/ServiceArea/serviceArea.routes';

import { EventTypeRoutes } from '../modules/EventType/eventType.routes';
import { VendorServiceRoutes } from '../modules/VendorService/vendorService.routes';
import { ServicePackageRoutes } from '../modules/ServicePackage/package.routes';
import { EventRequestRoutes } from '../modules/EventRequest/eventRequest.routes';
import { EventQuoteRoutes } from '../modules/EventQuote/eventQuote.routes';
import { VendorQuoteRoutes } from '../modules/VendorQuote/vendorQuote.routes';
import { InspirationRoutes } from '../modules/Inspiration/inspiration.routes';
import { BlogRoutes } from '../modules/Blog/blog/blog.routes';
import { BlogCategoryRoutes } from '../modules/Blog/blogCategory/blogCategory.routes';
import { BannerRoutes } from '../modules/Banner/banner.routes';
import { PromotionRoutes } from '../modules/Promotion/promotion.routes';
import { VerificationRoutes } from '../modules/Verification/verification.routes';
import { NewsletterRoutes } from '../modules/Newsletter/newsletter.routes';
import { AdvisorRoutes } from '../modules/Advisor/advisor.routes';
import { DashboardRoutes } from '../modules/Dashboard/dashboard.routes';
import { AnalyticsRoutes } from '../modules/Analytics/analytics.routes';
import { ChatRoutes } from '../modules/Chat/chat.routes';
import { DisputeRoutes } from '../modules/Dispute/dispute.routes';
import { ReportRoutes } from '../modules/Report/report.routes';


import refundPolicyRouter from '../modules/RefundPolicy/refundPolicy.routes';
import cookiePolicyRouter from '../modules/CookiePolicy/cookiePolicy.routes';
import footerRouter from '../modules/Footer/footer.routes';


const router = Router();

router.use('/auth', AuthRoutes);
router.use('/user', UserRoutes);
router.use('/about', aboutRouter);
router.use('/privacy', privacyPolicyRouter);
router.use('/refund-policy', refundPolicyRouter);
router.use('/cookie-policy', cookiePolicyRouter);
router.use('/footer', footerRouter);
router.use('/terms', termsRouter);
router.use('/faq', FaqRoutes);
router.use('/contact', ContactRoutes);
router.use('/notification', NotificationRoutes);
router.use('/reviews', ReviewRoutes);
router.use('/admin', AdminRoutes);
router.use('/category', CategoryRoutes);
router.use('/subcategory', SubcategoryRoutes);
router.use('/amenity', AmenityRoutes);
router.use('/service-area', ServiceAreaRoutes);
router.use('/vendor-service', VendorServiceRoutes);
router.use('/event-type', EventTypeRoutes);
router.use('/service-package', ServicePackageRoutes);
router.use('/event-request', EventRequestRoutes);
router.use('/event-quote', EventQuoteRoutes);
router.use('/vendor-quote', VendorQuoteRoutes);
router.use('/inspiration', InspirationRoutes);
router.use('/blog', BlogRoutes);
router.use('/blog-category', BlogCategoryRoutes);
router.use('/banner', BannerRoutes);
router.use('/promotion', PromotionRoutes);
router.use('/verification', VerificationRoutes);
router.use('/newsletter', NewsletterRoutes);
router.use('/advisor', AdvisorRoutes);
router.use('/dashboard', DashboardRoutes);
router.use('/analytics', AnalyticsRoutes);
router.use('/chat', ChatRoutes);
router.use('/dispute', DisputeRoutes);
router.use('/reports', ReportRoutes);

export default router;
